force-app/main/default/objects/copado__User_Story__c/copado__User_Story__c.object-meta.xml
<CustomObject>
    <description>Agile form of requirements gathering</description>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000000}</displayFormat>
        <label>User Story Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/copado__User_Story__c/fields/Is_Bundle__c.field-meta.xml
<CustomField>
    <fullName>Is_Bundle__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates when a User Story is a Bundle</description>
    <label>Is Bundle</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CUSB_UserStoryBundleTriggerHelper.cls
public with sharing class CUSB_UserStoryBundleTriggerHelper {
    public static void moveChildUserStoriesAcrossEnvironments(Map<Id, copado__User_Story__c> usNew, Map<Id, copado__User_Story__c> usOld) {
        List<copado__User_Story__c> changedUserStories = new List<copado__User_Story__c>();
        List<Id> changedUserStoryIds = new List<Id>();
        for (copado__User_Story__c userStoryItem : usNew.values()) {
            if (userStoryItem.Is_Bundle__c && userStoryItem.copado__Org_Credential__c != usOld.get(userStoryItem.Id).copado__Org_Credential__c) {
                changedUserStories.add(userStoryItem);
                changedUserStoryIds.add(userStoryItem.Id);
            }
        }
        if (!changedUserStoryIds.isEmpty()) {
            System.enqueueJob(new CUSB_UserStoryBundleQueueable(usNew, usOld, changedUserStories, changedUserStoryIds));
        }
    }
}